POST http://localhost:8000/api/offer/search/byCoach
Content-Type: application/json

{
  "firstName": "obaydah",
  "lastName": "bouifadene"
}
#####
# new request
POST http://localhost:8000/api/offer/add
Content-Type: application/json

{
  "id": 2,
  "name": "offer-temp",
  "description": "offer2 description",
  "price": "100",
  "coach": {
    "id": 2

  }
}

#####
# new request
POST http://localhost:8000/api/offer/search/byTags
Content-Type: application/json

[
  "nutrition"
]
#####
# new request
POST http://localhost:8000/api/offer/search/byTitle
Content-Type: text/plain

offer2